# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 793804533b81b1dba8cf91381be91e764053da73040c3a90ee92f152dac5a22211bb9d3080094a799a1ecb31f954479f72f2b3e6d8021631bd19fe9ba604a6c9

test:
  secret_key_base: 823ad72e2cee729d2da99bd90749742190cdf863c3f934d4c68530e5c7d8bd1ab0b7b028dc2f9df95abd0bb80667775d24fe5d404b81e2a8d7cb708e0221594b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
